@echo off
echo "                 _.-^^---....,,--                    "              
echo "             _--                  --_                "                
echo "            <         MONKEY       >)                "              
echo "             |        ROBOTS       |                 "            
echo "              \._       GO TO      _./               "           
echo "                 '''--.  MARS  .--'''                "                
echo "                                                     " 
echo "               ()   ()   ()   ()   ()                "    
echo "              /||\ /||\ /||\ /||\ /||\               "       
echo "                                                     "    
echo "                                                     "             
echo "         A tale of monkeys, robots they be,          " 
echo "      Engineered to travel, across the galaxy.       " 
echo "  To Mars they soared, their hearts full of flame,   "    
echo " But to start the journey, an IDF file was the name. "
echo "                                                     "       
echo "        One fateful launch, a file went awry,        "    
echo "    Wrong coordinates sent them far from the sky.    "        
echo "        Wandered they did, lost in deep space,       "      
echo "      Their souls now haunting the cosmic place.     "       
echo "                                                     "        
echo "  Black matter they eat, they've grown oh so large,  "        
echo "     Falling stars they hurl, an eerie barrage.      "          
echo "      But Guust Delbaere, with wisdom and care,      "          
echo "    Programmed the IDF tool with a masters flair.    "            
echo "                                                     "                 
echo "        Now every launch is safe and precise,        "             
echo "    Each rocket returning, no need to think twice.   "                  
echo "        Since that day, none have been harmed,       "                 
echo "         Guust's IDF tool keeps all alarmed.         "                   
echo "                                                     "                  
echo "   ()    Mars awaits, and the stars now glow,        "              
echo "  /||\  With monkey robots in a flawless show.       "                  
echo "   ()      The IDF tool has paved the way,           "                   
echo "  /||\    Ensuring no more shall ever stray.         "               
echo "                                                     "                 
echo "                  ~ THE END ~                        "                  

start "" "http://127.0.0.1:8000"
python idf_tool/app.py
pause